### ISSUE TITLE
Cannot cast to Linear Layout

### ISSUE THREAD

**Issue by MedveDomg** [TR4Android/Swipeable-RecyclerView#18]
I have this exception:
java.lang.ClassCastException: android.widget.FrameLayout cannot be cast to com.tr4android.recyclerviewslideitem.SwipeItem

and it depends on main type of my row layout.

**Comment by taltstidl** [comment]
@MedveDomg Can you provide the code fragment that's triggering this issue, please? Without more context it's hard to tell what's wrong here. Thanks!

**Comment by MedveDomg** [comment]
Sorry, I actually deleted code

**Comment by taltstidl** [comment]
@MedveDomg If it's working for you now, please close this issue. Without more code I'm unable to help you here, unfortunately. Thanks!
