### ISSUE TITLE
Add `onItemClick()` callback

### ISSUE THREAD

**Issue by DenisMondon** [TR4Android/Swipeable-RecyclerView#9]
Hi,

Nice library!
I was wondering how to implement an OnItemClickListener for each item.
Do you have any ideas?

Thanks.
Denis

**Comment by taltstidl** [comment]
@DenisMondon Handling click events is not covered by this library as its primary aim was to add simple support for swiping list items. You should refer to other resources on the web for this instead (such as http://www.littlerobots.nl/blog/Handle-Android-RecyclerView-Clicks/).
Seeing how difficult this has become though, I might consider adding a callback for this similiar to the `onSwipe()` callback in the future.

**Comment by DenisMondon** [comment]
@TR4Android Thanks for the answer :)
I will read this article :)
And I think it could be a good feature like onSwipe()!! ;)

Thanks!

**Comment by taltstidl** [comment]
@DenisMondon Sure :smiley: Like I said, I will look into adding this in the future, for now you'll have to implement click handling yourself though.

**Comment by DenisMondon** [comment]
The article works with my "normal" Adapter (without swipe), but not with yours (SwipeAdapter).
For me, the only code that changes is:

``` java
return new ViewHolder(layoutInflater.inflate(R.layout.my_layout, parent, false);
```

Your code uses true (for the attachToRoot parameter).

Do you have any ideas?

**Comment by taltstidl** [comment]
@DenisMondon I'll look into this and add support for item clicks as soon as I can! Bear with me.

**Comment by taltstidl** [comment]
@DenisMondon What excactly does not work? Is the click never registered or is there an exception?

**Comment by DenisMondon** [comment]
The click is never registered...

**Comment by taltstidl** [comment]
@DenisMondon You could try setting your click listener to a specific `View` (using an id). Does that work?

**Comment by taltstidl** [comment]
@DenisMondon I decided against this as it's pretty simple to implement actually. I did however update the sample code to reflect this and added click listener to the items there (see commit 0ad6e5d147e608e29db14d0b9ddfb42a28fbe9ee and the updated [`SampleAdapter`](https://github.com/TR4Android/Swipeable-RecyclerView/blob/master/sample/src/main/java/com/tr4android/recyclerviewslideitemsample/SampleAdapter.java) and [`item_sample`](https://github.com/TR4Android/Swipeable-RecyclerView/blob/master/sample/src/main/res/layout/item_sample.xml))
I'm closing this in favor of developers own implementations. If you have any trouble getting the sample code to work for you, you can still ask for help here.
